version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/step2/zip/
    overwrite: yes

#version : 0.0 : CodeDeploy의 버전을 말함, 프로젝트 버젼이 아니므로 0.0외의 다른 버젼 사용시 오류발생
#source : CodeDeploy에서 전달해준 파일 중 destination으로 이동시킬 대상을 지정
#         /(루트)경로를 지정하면 전체 파일을 이야기함
#destination : source에서 지정된 파일을 받을 위치, 이후 Jar를 실행하는 등은 destination에서 옮긴 파일들로 진행
#overwrite : 기존에 파일들이 있으면 덮어 쓸지를 결정