version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/step3/zip/
    overwrite: yes

#permissions : CodeDeploy에서 EC2 서버로 넘겨준 파일들을 모두 ec2-user 권한ㅇ르 갖도록 함~
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

#hooks : CodeDeploy 배포 단계에서 실행할 명령어를 지정
#ApplicationStart라는 단계에서 deploy.sh를 ec2-user 권한으로 실행하게 함
#timeout : 60으로 스크립트 실행 60초 이상 수행되면 실패가 됨(무작정 기다릴 수 없으니 시간 제한 둬야함)
hooks:
  AfterInstall:
    - location: stop.sh #엔진엑스와 연결되어 있진 않지만, 실행중이던 스트링 부트 종류
      timeout: 60
      runas: ec2-user
  ApplicationStart: #엔진엑스와 연겨되어 있지 않는 Port로 새버전의 스프링부트를 시작
    - location: start.sh
      timeout: 60
      runas: ec2-user
  ValidateSerivce:
    - location: health.sh #새 스프링 부트가 정상적으로 실행됐는지 확인
      timeout: 60
      runas: ec2-user

#version : 0.0 : CodeDeploy의 버전을 말함, 프로젝트 버젼이 아니므로 0.0외의 다른 버젼 사용시 오류발생
#source : CodeDeploy에서 전달해준 파일 중 destination으로 이동시킬 대상을 지정
#         /(루트)경로를 지정하면 전체 파일을 이야기함
#destination : source에서 지정된 파일을 받을 위치, 이후 Jar를 실행하는 등은 destination에서 옮긴 파일들로 진행
#overwrite : 기존에 파일들이 있으면 덮어 쓸지를 결정